In [1]:
lorem = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis. Quisque in auctor elit. Nulla et aliquet turpis. Maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada. Cras sodales ipsum et tellus lacinia, ut mattis elit vehicula. Nunc quam quam, cursus quis leo quis, sagittis pellentesque eros. Donec nec nulla in sem bibendum tristique vel tempus metus.
Etiam scelerisque nulla vel egestas feugiat. Aenean sed consectetur urna. Sed nisl mi, imperdiet a tincidunt eget, varius nec dui. In porta risus id bibendum viverra. Pellentesque tristique quam dolor, sed tempor orci hendrerit ut. Suspendisse id lectus vel massa varius fringilla non ac orci. Etiam nec odio hendrerit, dignissim justo sed, convallis nibh. Pellentesque bibendum euismod erat, ac congue purus tincidunt eu.
Praesent diam enim, sollicitudin quis mi id, tristique laoreet nisi. Donec faucibus tellus at libero malesuada sagittis. Quisque condimentum porta luctus. Quisque sagittis ut purus ac auctor. Nulla eget porttitor turpis, eget finibus tortor. Sed vitae convallis justo. Aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus. Duis in nisi ac sem gravida venenatis. Nullam non eros nec mauris rhoncus dapibus. Sed rhoncus ornare ligula nec placerat. Sed augue enim, semper quis sapien at, lacinia mollis nisi. Nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus.
Integer sit amet ex quis felis pellentesque facilisis. Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros. Vestibulum faucibus est massa. Nunc ante massa, congue nec tortor ut, bibendum facilisis tellus. Praesent non ex et mi fermentum sollicitudin. In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. Donec et hendrerit libero, sit amet dictum leo. Nam id posuere turpis, in vulputate erat. In nec metus ut justo congue dignissim. Maecenas lobortis volutpat venenatis. Integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra. Proin tincidunt finibus tincidunt.
Vestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor. Maecenas pellentesque malesuada ligula nec cursus. Sed augue erat, hendrerit sed tincidunt a, facilisis id enim. Pellentesque in massa pretium, aliquam urna commodo, maximus urna. Etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie. Quisque posuere nibh vitae ante varius congue. Nullam ut ipsum auctor, dapibus justo ut, volutpat magna. Nam tristique molestie arcu in ornare. Aenean cursus pellentesque faucibus. Ut dapibus fringilla aliquam.'''

In [2]:
lorem

'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis. Quisque in auctor elit. Nulla et aliquet turpis. Maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada. Cras sodales ipsum et tellus lacinia, ut mattis elit vehicula. Nunc quam quam, cursus quis leo quis, sagittis pellentesque eros. Donec nec nulla in sem bibendum tristique vel tempus metus.\nEtiam scelerisque nulla vel egestas feugiat. Aenean sed consectetur urna. Sed nisl mi, imperdiet a tincidunt eget, varius nec dui. In porta risus id bibendum viverra. Pellentesque tristique quam dolor, sed tempor orci hendrerit ut. Suspendisse id lectus vel massa varius fringilla non ac orci. Etiam nec odio hendrerit, dignissim justo sed, convallis nibh. Pellentesque bibendum euismod erat, ac congue purus tincidunt eu.\nPraesent diam enim, sollicitudin quis mi id, tristique laoreet nisi. Donec faucibus tellus at libero malesuada sagittis. Quisque condimentum porta luctus. Quisque sagittis ut purus ac auctor. Nulla eget porttitor turpis, eget finibus tortor. Sed vitae convallis justo. Aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus. Duis in nisi ac sem gravida venenatis. Nullam non eros nec mauris rhoncus dapibus. Sed rhoncus ornare ligula nec placerat. Sed augue enim, semper quis sapien at, lacinia mollis nisi. Nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus.\nInteger sit amet ex quis felis pellentesque facilisis. Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros. Vestibulum faucibus est massa. Nunc ante massa, congue nec tortor ut, bibendum facilisis tellus. Praesent non ex et mi fermentum sollicitudin. In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. Donec et hendrerit libero, sit amet dictum leo. Nam id posuere turpis, in vulputate erat. In nec metus ut justo congue dignissim. Maecenas lobortis volutpat venenatis. Integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra. Proin tincidunt finibus tincidunt.\nVestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor. Maecenas pellentesque malesuada ligula nec cursus. Sed augue erat, hendrerit sed tincidunt a, facilisis id enim. Pellentesque in massa pretium, aliquam urna commodo, maximus urna. Etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie. Quisque posuere nibh vitae ante varius congue. Nullam ut ipsum auctor, dapibus justo ut, volutpat magna. Nam tristique molestie arcu in ornare. Aenean cursus pellentesque faucibus. Ut dapibus fringilla aliquam.'

In [3]:
lorem[10]

'm'

In [4]:
lorem[10:20]

'm dolor si'

In [7]:
lorem[10:100:2] #2글자 마다 보여주는것

'mdlrstae,cnettraiicn lt eenlbri ut gtlcspsee '

* lorem 문자열에서, 뒤에서 세번째부터 앞에서 10번째까지 글자가 뭐가 있는지 출력해보세요.

In [11]:
lorem[-3:10:-1]

'auqila allignirf subipad tU .subicuaf euqsetnellep susruc naeneA .eranro ni ucra eitselom euqitsirt maN .angam taptulov ,tu otsuj subipad ,rotcua muspi tu malluN .eugnoc suirav etna eativ hbin ereusop euqsiuQ .eitselom euqen eranro eativ ,euqsirelecs rotrot ca allun subinif maitE .anru sumixam ,odommoc anru mauqila ,muiterp assam ni euqsetnelleP .mine di sisilicaf ,a tnudicnit des tirerdneh ,tare eugua deS .susruc cen alugil adauselam euqsetnellep saneceaM .rolod sucnohr ,non anru tarecalp ,subipad sucal eativ mulubitseV\n.tnudicnit subinif tnudicnit niorP .arreviv sore niduticillos di ,ropmet mes tu rolod sucnohr regetnI .sitanenev taptulov sitrobol saneceaM .missingid eugnoc otsuj tu sutem cen nI .tare etatupluv ni ,siprut ereusop di maN .oel mutcid tema tis ,orebil tirerdneh te cenoD .angam odommoc ,teuqila muspi mutcid ,taptulov tse niduticillos nI .niduticillos mutnemref im te xe non tnesearP .sullet sisilicaf mudnebib ,tu rotrot cen eugnoc ,assam etna cnuN .assam tse subicuaf mulubitseV .sore mulubitsev euqsetnellep ,siuq angam euqsetnellep mudnebib ,sutem sucal mauqilA .sisilicaf euqsetnellep silef siuq xe tema tis regetnI\n.sutcel non silef mine ropmet tu ,assam sillom orebil sutcel ,domsiue tipicsus eativ cnun ,ranivlup malluN .isin sillom ainical ,ta neipas siuq repmes ,mine eugua deS .tarecalp cen alugil eranro sucnohr deS .subipad sucnohr siruam cen sore non malluN .sitanenev adivarg mes ca isin ni siuD .susir mauqila sitrobol ,cen siruam tema tis sutcul ,silef angam naeneA .otsuj sillavnoc eativ deS .rotrot subinif tege ,siprut rotittrop tege alluN .rotcua ca surup tu sittigas euqsiuQ .sutcul atrop mutnemidnoc euqsiuQ .sittigas adauselam orebil ta sullet subicuaf cenoD .isin teeroal euqitsirt ,di im siuq niduticillos ,mine maid tnesearP\n.ue tnudicnit surup eugnoc ca ,tare domsiue mudnebib euqsetnelleP .hbin sillavnoc ,des otsuj missingid ,tirerdneh oido cen maitE .icro ca non allignirf suirav assam lev sutcel di essidnepsuS .tu tirerdneh icro ropmet des ,rolod mauq euqitsirt euqsetnelleP .arreviv mudnebib di susir atrop nI .iud cen suirav ,tege tnudicnit a teidrepmi ,im lsin deS .anru rutetcesnoc des naeneA .taiguef satsege lev allun euqsirelecs maitE\n.sutem supmet lev euqitsirt mudnebib mes ni allun cen cenoD .sore euqsetnellep sittigas ,siuq oel siuq susruc ,mauq mauq cnuN .alucihev tile sittam tu ,ainical sullet te muspi selados sarC .adauselam eranro mes selados ue ,assam teeroal teidrepmi saneceaM .siprut teuqila te alluN .tile rotcua ni euqsiuQ .silucai tilev euqitsirt cen ,ereusop sucal tege otsuj sitrobol naeneA .tile gnicsipida rutetcesnoc ,tema tis rolod '

# 문자열 포멧팅

# 방법1 (외워라)
* f를 따옴표 밖에 쓴다.
* {} 안에 리스트나 변수, 데이터 프레임, 숫자 등을 넣는다.

In [10]:
# 앞에서 3번째
v1 = lorem[3]

# 뒤에서 3번째
v2 = lorem[-3]

# 범위
v3 = lorem[1:5]

msg = f'''앞에서 3번째를 알아보려면 {v1}을 치고,
뒤에서 3번째를 알아보려면 {v2}를 치고,
1~5번째 범위를 알아보면 {v3}이 나옵니다.'''

print(msg)

앞에서 3번째를 알아보려면 e을 치고,
뒤에서 3번째를 알아보려면 a를 치고,
1~5번째 범위를 알아보면 orem이 나옵니다.

# 방법2

In [12]:
print('앞에서 3번째를 알아보려면')
print('v1')
print('이 나옵니다.')

앞에서 3번째를 알아보려면
v1
이 나옵니다.

In [13]:
print('앞에서 3번째를 알아보려면', v1 ,'이 나옵니다.')

앞에서 3번째를 알아보려면 e 이 나옵니다.

# 방법3 (옛날방법, 비추)
* 무조건 순서를 지켜야함

In [14]:
'''앞에서 3번째를 알아보려면 %s이 치고,
뒤에서 3번째를 알아보려면 %s이 치고,
1~5번째 범위를 알아보면 %s이 나옵니다.''' %(v1,v2,v3)

'앞에서 3번째를 알아보려면 e이 치고,\n뒤에서 3번째를 알아보려면 a이 치고,\n1~5번째 범위를 알아보면 orem이 나옵니다.'

# 방법4

In [16]:
'''앞에서 3번째를 알아보려면 {}을 치고,
뒤에서 3번째를 알아보려면 {}를 치고,
1~5번째 범위를 알아보면 {}이 나옵니다.'''.format(v1,v2,v3)

'앞에서 3번째를 알아보려면 e을 치고,\n뒤에서 3번째를 알아보려면 a를 치고,\n1~5번째 범위를 알아보면 orem이 나옵니다.'

* lorem에서 소문자 r을 모두 대문자 R로 바꿔봅시다.

In [19]:
lorem

'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis. Quisque in auctor elit. Nulla et aliquet turpis. Maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada. Cras sodales ipsum et tellus lacinia, ut mattis elit vehicula. Nunc quam quam, cursus quis leo quis, sagittis pellentesque eros. Donec nec nulla in sem bibendum tristique vel tempus metus.\nEtiam scelerisque nulla vel egestas feugiat. Aenean sed consectetur urna. Sed nisl mi, imperdiet a tincidunt eget, varius nec dui. In porta risus id bibendum viverra. Pellentesque tristique quam dolor, sed tempor orci hendrerit ut. Suspendisse id lectus vel massa varius fringilla non ac orci. Etiam nec odio hendrerit, dignissim justo sed, convallis nibh. Pellentesque bibendum euismod erat, ac congue purus tincidunt eu.\nPraesent diam enim, sollicitudin quis mi id, tristique laoreet nisi. Donec faucibus tellus at libero malesuada sagittis. Quisque condimentum porta luctus. Quisque sagittis ut purus ac auctor. Nulla eget porttitor turpis, eget finibus tortor. Sed vitae convallis justo. Aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus. Duis in nisi ac sem gravida venenatis. Nullam non eros nec mauris rhoncus dapibus. Sed rhoncus ornare ligula nec placerat. Sed augue enim, semper quis sapien at, lacinia mollis nisi. Nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus.\nInteger sit amet ex quis felis pellentesque facilisis. Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros. Vestibulum faucibus est massa. Nunc ante massa, congue nec tortor ut, bibendum facilisis tellus. Praesent non ex et mi fermentum sollicitudin. In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. Donec et hendrerit libero, sit amet dictum leo. Nam id posuere turpis, in vulputate erat. In nec metus ut justo congue dignissim. Maecenas lobortis volutpat venenatis. Integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra. Proin tincidunt finibus tincidunt.\nVestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor. Maecenas pellentesque malesuada ligula nec cursus. Sed augue erat, hendrerit sed tincidunt a, facilisis id enim. Pellentesque in massa pretium, aliquam urna commodo, maximus urna. Etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie. Quisque posuere nibh vitae ante varius congue. Nullam ut ipsum auctor, dapibus justo ut, volutpat magna. Nam tristique molestie arcu in ornare. Aenean cursus pellentesque faucibus. Ut dapibus fringilla aliquam.'

In [20]:
lorem.replace('r','R')

'LoRem ipsum doloR sit amet, consectetuR adipiscing elit. Aenean loboRtis justo eget lacus posueRe, nec tRistique velit iaculis. Quisque in auctoR elit. Nulla et aliquet tuRpis. Maecenas impeRdiet laoReet massa, eu sodales sem oRnaRe malesuada. CRas sodales ipsum et tellus lacinia, ut mattis elit vehicula. Nunc quam quam, cuRsus quis leo quis, sagittis pellentesque eRos. Donec nec nulla in sem bibendum tRistique vel tempus metus.\nEtiam sceleRisque nulla vel egestas feugiat. Aenean sed consectetuR uRna. Sed nisl mi, impeRdiet a tincidunt eget, vaRius nec dui. In poRta Risus id bibendum viveRRa. Pellentesque tRistique quam doloR, sed tempoR oRci hendReRit ut. Suspendisse id lectus vel massa vaRius fRingilla non ac oRci. Etiam nec odio hendReRit, dignissim justo sed, convallis nibh. Pellentesque bibendum euismod eRat, ac congue puRus tincidunt eu.\nPRaesent diam enim, sollicitudin quis mi id, tRistique laoReet nisi. Donec faucibus tellus at libeRo malesuada sagittis. Quisque condimentum poRta luctus. Quisque sagittis ut puRus ac auctoR. Nulla eget poRttitoR tuRpis, eget finibus toRtoR. Sed vitae convallis justo. Aenean magna felis, luctus sit amet mauRis nec, loboRtis aliquam Risus. Duis in nisi ac sem gRavida venenatis. Nullam non eRos nec mauRis Rhoncus dapibus. Sed Rhoncus oRnaRe ligula nec placeRat. Sed augue enim, sempeR quis sapien at, lacinia mollis nisi. Nullam pulvinaR, nunc vitae suscipit euismod, lectus libeRo mollis massa, ut tempoR enim felis non lectus.\nIntegeR sit amet ex quis felis pellentesque facilisis. Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eRos. Vestibulum faucibus est massa. Nunc ante massa, congue nec toRtoR ut, bibendum facilisis tellus. PRaesent non ex et mi feRmentum sollicitudin. In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. Donec et hendReRit libeRo, sit amet dictum leo. Nam id posueRe tuRpis, in vulputate eRat. In nec metus ut justo congue dignissim. Maecenas loboRtis volutpat venenatis. IntegeR Rhoncus doloR ut sem tempoR, id sollicitudin eRos viveRRa. PRoin tincidunt finibus tincidunt.\nVestibulum vitae lacus dapibus, placeRat uRna non, Rhoncus doloR. Maecenas pellentesque malesuada ligula nec cuRsus. Sed augue eRat, hendReRit sed tincidunt a, facilisis id enim. Pellentesque in massa pRetium, aliquam uRna commodo, maximus uRna. Etiam finibus nulla ac toRtoR sceleRisque, vitae oRnaRe neque molestie. Quisque posueRe nibh vitae ante vaRius congue. Nullam ut ipsum auctoR, dapibus justo ut, volutpat magna. Nam tRistique molestie aRcu in oRnaRe. Aenean cuRsus pellentesque faucibus. Ut dapibus fRingilla aliquam.'

# upper(), lower()
## 전부 대문자, 소문자

In [21]:
lorem.upper()

'LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. AENEAN LOBORTIS JUSTO EGET LACUS POSUERE, NEC TRISTIQUE VELIT IACULIS. QUISQUE IN AUCTOR ELIT. NULLA ET ALIQUET TURPIS. MAECENAS IMPERDIET LAOREET MASSA, EU SODALES SEM ORNARE MALESUADA. CRAS SODALES IPSUM ET TELLUS LACINIA, UT MATTIS ELIT VEHICULA. NUNC QUAM QUAM, CURSUS QUIS LEO QUIS, SAGITTIS PELLENTESQUE EROS. DONEC NEC NULLA IN SEM BIBENDUM TRISTIQUE VEL TEMPUS METUS.\nETIAM SCELERISQUE NULLA VEL EGESTAS FEUGIAT. AENEAN SED CONSECTETUR URNA. SED NISL MI, IMPERDIET A TINCIDUNT EGET, VARIUS NEC DUI. IN PORTA RISUS ID BIBENDUM VIVERRA. PELLENTESQUE TRISTIQUE QUAM DOLOR, SED TEMPOR ORCI HENDRERIT UT. SUSPENDISSE ID LECTUS VEL MASSA VARIUS FRINGILLA NON AC ORCI. ETIAM NEC ODIO HENDRERIT, DIGNISSIM JUSTO SED, CONVALLIS NIBH. PELLENTESQUE BIBENDUM EUISMOD ERAT, AC CONGUE PURUS TINCIDUNT EU.\nPRAESENT DIAM ENIM, SOLLICITUDIN QUIS MI ID, TRISTIQUE LAOREET NISI. DONEC FAUCIBUS TELLUS AT LIBERO MALESUADA SAGITTIS. QUISQUE CONDIMENTUM PORTA LUCTUS. QUISQUE SAGITTIS UT PURUS AC AUCTOR. NULLA EGET PORTTITOR TURPIS, EGET FINIBUS TORTOR. SED VITAE CONVALLIS JUSTO. AENEAN MAGNA FELIS, LUCTUS SIT AMET MAURIS NEC, LOBORTIS ALIQUAM RISUS. DUIS IN NISI AC SEM GRAVIDA VENENATIS. NULLAM NON EROS NEC MAURIS RHONCUS DAPIBUS. SED RHONCUS ORNARE LIGULA NEC PLACERAT. SED AUGUE ENIM, SEMPER QUIS SAPIEN AT, LACINIA MOLLIS NISI. NULLAM PULVINAR, NUNC VITAE SUSCIPIT EUISMOD, LECTUS LIBERO MOLLIS MASSA, UT TEMPOR ENIM FELIS NON LECTUS.\nINTEGER SIT AMET EX QUIS FELIS PELLENTESQUE FACILISIS. ALIQUAM LACUS METUS, BIBENDUM PELLENTESQUE MAGNA QUIS, PELLENTESQUE VESTIBULUM EROS. VESTIBULUM FAUCIBUS EST MASSA. NUNC ANTE MASSA, CONGUE NEC TORTOR UT, BIBENDUM FACILISIS TELLUS. PRAESENT NON EX ET MI FERMENTUM SOLLICITUDIN. IN SOLLICITUDIN EST VOLUTPAT, DICTUM IPSUM ALIQUET, COMMODO MAGNA. DONEC ET HENDRERIT LIBERO, SIT AMET DICTUM LEO. NAM ID POSUERE TURPIS, IN VULPUTATE ERAT. IN NEC METUS UT JUSTO CONGUE DIGNISSIM. MAECENAS LOBORTIS VOLUTPAT VENENATIS. INTEGER RHONCUS DOLOR UT SEM TEMPOR, ID SOLLICITUDIN EROS VIVERRA. PROIN TINCIDUNT FINIBUS TINCIDUNT.\nVESTIBULUM VITAE LACUS DAPIBUS, PLACERAT URNA NON, RHONCUS DOLOR. MAECENAS PELLENTESQUE MALESUADA LIGULA NEC CURSUS. SED AUGUE ERAT, HENDRERIT SED TINCIDUNT A, FACILISIS ID ENIM. PELLENTESQUE IN MASSA PRETIUM, ALIQUAM URNA COMMODO, MAXIMUS URNA. ETIAM FINIBUS NULLA AC TORTOR SCELERISQUE, VITAE ORNARE NEQUE MOLESTIE. QUISQUE POSUERE NIBH VITAE ANTE VARIUS CONGUE. NULLAM UT IPSUM AUCTOR, DAPIBUS JUSTO UT, VOLUTPAT MAGNA. NAM TRISTIQUE MOLESTIE ARCU IN ORNARE. AENEAN CURSUS PELLENTESQUE FAUCIBUS. UT DAPIBUS FRINGILLA ALIQUAM.'

In [22]:
lorem.lower()

'lorem ipsum dolor sit amet, consectetur adipiscing elit. aenean lobortis justo eget lacus posuere, nec tristique velit iaculis. quisque in auctor elit. nulla et aliquet turpis. maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada. cras sodales ipsum et tellus lacinia, ut mattis elit vehicula. nunc quam quam, cursus quis leo quis, sagittis pellentesque eros. donec nec nulla in sem bibendum tristique vel tempus metus.\netiam scelerisque nulla vel egestas feugiat. aenean sed consectetur urna. sed nisl mi, imperdiet a tincidunt eget, varius nec dui. in porta risus id bibendum viverra. pellentesque tristique quam dolor, sed tempor orci hendrerit ut. suspendisse id lectus vel massa varius fringilla non ac orci. etiam nec odio hendrerit, dignissim justo sed, convallis nibh. pellentesque bibendum euismod erat, ac congue purus tincidunt eu.\npraesent diam enim, sollicitudin quis mi id, tristique laoreet nisi. donec faucibus tellus at libero malesuada sagittis. quisque condimentum porta luctus. quisque sagittis ut purus ac auctor. nulla eget porttitor turpis, eget finibus tortor. sed vitae convallis justo. aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus. duis in nisi ac sem gravida venenatis. nullam non eros nec mauris rhoncus dapibus. sed rhoncus ornare ligula nec placerat. sed augue enim, semper quis sapien at, lacinia mollis nisi. nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus.\ninteger sit amet ex quis felis pellentesque facilisis. aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros. vestibulum faucibus est massa. nunc ante massa, congue nec tortor ut, bibendum facilisis tellus. praesent non ex et mi fermentum sollicitudin. in sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. donec et hendrerit libero, sit amet dictum leo. nam id posuere turpis, in vulputate erat. in nec metus ut justo congue dignissim. maecenas lobortis volutpat venenatis. integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra. proin tincidunt finibus tincidunt.\nvestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor. maecenas pellentesque malesuada ligula nec cursus. sed augue erat, hendrerit sed tincidunt a, facilisis id enim. pellentesque in massa pretium, aliquam urna commodo, maximus urna. etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie. quisque posuere nibh vitae ante varius congue. nullam ut ipsum auctor, dapibus justo ut, volutpat magna. nam tristique molestie arcu in ornare. aenean cursus pellentesque faucibus. ut dapibus fringilla aliquam.'

# 띄어쓰기 제거

In [24]:
lorem.replace(' ','')

'Loremipsumdolorsitamet,consecteturadipiscingelit.Aeneanlobortisjustoegetlacusposuere,nectristiquevelitiaculis.Quisqueinauctorelit.Nullaetaliquetturpis.Maecenasimperdietlaoreetmassa,eusodalessemornaremalesuada.Crassodalesipsumettelluslacinia,utmattiselitvehicula.Nuncquamquam,cursusquisleoquis,sagittispellentesqueeros.Donecnecnullainsembibendumtristiqueveltempusmetus.\nEtiamscelerisquenullavelegestasfeugiat.Aeneansedconsectetururna.Sednislmi,imperdietatincidunteget,variusnecdui.Inportarisusidbibendumviverra.Pellentesquetristiquequamdolor,sedtempororcihendreritut.Suspendisseidlectusvelmassavariusfringillanonacorci.Etiamnecodiohendrerit,dignissimjustosed,convallisnibh.Pellentesquebibendumeuismoderat,acconguepurustincidunteu.\nPraesentdiamenim,sollicitudinquismiid,tristiquelaoreetnisi.Donecfaucibustellusatliberomalesuadasagittis.Quisquecondimentumportaluctus.Quisquesagittisutpurusacauctor.Nullaegetporttitorturpis,egetfinibustortor.Sedvitaeconvallisjusto.Aeneanmagnafelis,luctussitametmaurisnec,lobortisaliquamrisus.Duisinnisiacsemgravidavenenatis.Nullamnonerosnecmaurisrhoncusdapibus.Sedrhoncusornareligulanecplacerat.Sedaugueenim,semperquissapienat,laciniamollisnisi.Nullampulvinar,nuncvitaesuscipiteuismod,lectusliberomollismassa,uttemporenimfelisnonlectus.\nIntegersitametexquisfelispellentesquefacilisis.Aliquamlacusmetus,bibendumpellentesquemagnaquis,pellentesquevestibulumeros.Vestibulumfaucibusestmassa.Nuncantemassa,conguenectortorut,bibendumfacilisistellus.Praesentnonexetmifermentumsollicitudin.Insollicitudinestvolutpat,dictumipsumaliquet,commodomagna.Donecethendreritlibero,sitametdictumleo.Namidposuereturpis,invulputateerat.Innecmetusutjustoconguedignissim.Maecenaslobortisvolutpatvenenatis.Integerrhoncusdolorutsemtempor,idsollicitudinerosviverra.Prointinciduntfinibustincidunt.\nVestibulumvitaelacusdapibus,placeraturnanon,rhoncusdolor.Maecenaspellentesquemalesuadaligulaneccursus.Sedaugueerat,hendreritsedtincidunta,facilisisidenim.Pellentesqueinmassapretium,aliquamurnacommodo,maximusurna.Etiamfinibusnullaactortorscelerisque,vitaeornarenequemolestie.Quisqueposuerenibhvitaeantevariuscongue.Nullamutipsumauctor,dapibusjustout,volutpatmagna.Namtristiquemolestiearcuinornare.Aeneancursuspellentesquefaucibus.Utdapibusfringillaaliquam.'

# 문자열을 다루는 다른 함수

In [25]:
lorem.split('.')

['Lorem ipsum dolor sit amet, consectetur adipiscing elit',
 ' Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis',
 ' Quisque in auctor elit',
 ' Nulla et aliquet turpis',
 ' Maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada',
 ' Cras sodales ipsum et tellus lacinia, ut mattis elit vehicula',
 ' Nunc quam quam, cursus quis leo quis, sagittis pellentesque eros',
 ' Donec nec nulla in sem bibendum tristique vel tempus metus',
 '\nEtiam scelerisque nulla vel egestas feugiat',
 ' Aenean sed consectetur urna',
 ' Sed nisl mi, imperdiet a tincidunt eget, varius nec dui',
 ' In porta risus id bibendum viverra',
 ' Pellentesque tristique quam dolor, sed tempor orci hendrerit ut',
 ' Suspendisse id lectus vel massa varius fringilla non ac orci',
 ' Etiam nec odio hendrerit, dignissim justo sed, convallis nibh',
 ' Pellentesque bibendum euismod erat, ac congue purus tincidunt eu',
 '\nPraesent diam enim, sollicitudin quis mi id, tristique laoreet nisi',
 ' Donec faucibus tellus at libero malesuada sagittis',
 ' Quisque condimentum porta luctus',
 ' Quisque sagittis ut purus ac auctor',
 ' Nulla eget porttitor turpis, eget finibus tortor',
 ' Sed vitae convallis justo',
 ' Aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus',
 ' Duis in nisi ac sem gravida venenatis',
 ' Nullam non eros nec mauris rhoncus dapibus',
 ' Sed rhoncus ornare ligula nec placerat',
 ' Sed augue enim, semper quis sapien at, lacinia mollis nisi',
 ' Nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus',
 '\nInteger sit amet ex quis felis pellentesque facilisis',
 ' Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros',
 ' Vestibulum faucibus est massa',
 ' Nunc ante massa, congue nec tortor ut, bibendum facilisis tellus',
 ' Praesent non ex et mi fermentum sollicitudin',
 ' In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna',
 ' Donec et hendrerit libero, sit amet dictum leo',
 ' Nam id posuere turpis, in vulputate erat',
 ' In nec metus ut justo congue dignissim',
 ' Maecenas lobortis volutpat venenatis',
 ' Integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra',
 ' Proin tincidunt finibus tincidunt',
 '\nVestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor',
 ' Maecenas pellentesque malesuada ligula nec cursus',
 ' Sed augue erat, hendrerit sed tincidunt a, facilisis id enim',
 ' Pellentesque in massa pretium, aliquam urna commodo, maximus urna',
 ' Etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie',
 ' Quisque posuere nibh vitae ante varius congue',
 ' Nullam ut ipsum auctor, dapibus justo ut, volutpat magna',
 ' Nam tristique molestie arcu in ornare',
 ' Aenean cursus pellentesque faucibus',
 ' Ut dapibus fringilla aliquam',
 '']

In [26]:
'-'.join(['Lorem ipsum dolor sit amet, consectetur adipiscing elit',
 ' Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis'])

'Lorem ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis'

In [27]:
lorem2 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis'

# strip
* 문자열 대상으로 맨 앞과 맨 뒤에서 찾음.
* strip안에 있는 문자 중 겹치는게 있으면 삭제, 아니면 중지
* 왼쪽부터: lstrip
* 오른쪽부터: rstrip

In [28]:
lorem2

'Lorem ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis'

In [29]:
lorem2.strip('Lorem')

' ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis'

In [30]:
lorem2.strip('iaculis')

'Lorem ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit '

In [32]:
lorem2.strip('Lrsvti')

'orem ipsum dolor sit amet, consectetur adipiscing elit- Aenean lobortis justo eget lacus posuere, nec tristique velit iacul'

# 딕셔너리

In [42]:
dict = {'key':'value','key2':'value2','key3':'value3'}

In [43]:
dict['key2']

'value2'

In [44]:
dict2 = {'column':[1,2,3,4,5,6,7,8,9,0],'column2':[1,2,3,4,5,6,7,8,9,0],'column3':[1,2,3,4,5,6,7,8,9,0]}

In [45]:
dict2

{'column': [1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
 'column2': [1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
 'column3': [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]}

In [46]:
import pandas as pd

In [48]:
df = pd.DataFrame(dict2)

In [49]:
df

   column  column2  column3
0       1        1        1
1       2        2        2
2       3        3        3
3       4        4        4
4       5        5        5
5       6        6        6
6       7        7        7
7       8        8        8
8       9        9        9
9       0        0        0

In [50]:
df['column']

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
Name: column, dtype: int64

In [51]:
df.loc[2,'column2']

3

In [52]:
df.index = ['0','1','2','3','4','5','6','7','8','9']

In [55]:
df.loc['4','column3'] # 이름으로 찾기

5

In [56]:
df.iloc[4,2] # 숫자로 찾기

5

In [58]:
df.loc['2','column'] = 30

In [59]:
df

   column  column2  column3
0       1        1        1
1       2        2        2
2      30        3        3
3       4        4        4
4       5        5        5
5       6        6        6
6       7        7        7
7       8        8        8
8       9        9        9
9       0        0        0

In [61]:
df.loc['1'] = 20

In [62]:
df

   column  column2  column3
0       1        1        1
1      20       20       20
2      30        3        3
3       4        4        4
4       5        5        5
5       6        6        6
6       7        7        7
7       8        8        8
8       9        9        9
9       0        0        0

In [63]:
df.loc['3'] = [40,40,4]

In [64]:
df

   column  column2  column3
0       1        1        1
1      20       20       20
2      30        3        3
3      40       40        4
4       5        5        5
5       6        6        6
6       7        7        7
7       8        8        8
8       9        9        9
9       0        0        0

In [67]:
mean3 = df['column3'].mean()

In [69]:
col4 = df['column3'] > mean3

In [70]:
df.index = ['9','8','7','6','5','4','3','2','1','0']

In [71]:
df

   column  column2  column3
9       1        1        1
8      20       20       20
7      30        3        3
6      40       40        4
5       5        5        5
4       6        6        6
3       7        7        7
2       8        8        8
1       9        9        9
0       0        0        0

In [72]:
df['column4'] = col4

### col4 와 순서 일치X , df의 index 순서가 달라졌기때문에

In [76]:
df

   column  column2  column3  column4
9       1        1        1    False
8      20       20       20     True
7      30        3        3     True
6      40       40        4     True
5       5        5        5    False
4       6        6        6    False
3       7        7        7    False
2       8        8        8    False
1       9        9        9     True
0       0        0        0    False

In [138]:
col4

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9    False
Name: column3, dtype: bool

* lorem에서 소문자 a가 몇개 있나요?

In [77]:
lorem

'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis justo eget lacus posuere, nec tristique velit iaculis. Quisque in auctor elit. Nulla et aliquet turpis. Maecenas imperdiet laoreet massa, eu sodales sem ornare malesuada. Cras sodales ipsum et tellus lacinia, ut mattis elit vehicula. Nunc quam quam, cursus quis leo quis, sagittis pellentesque eros. Donec nec nulla in sem bibendum tristique vel tempus metus.\nEtiam scelerisque nulla vel egestas feugiat. Aenean sed consectetur urna. Sed nisl mi, imperdiet a tincidunt eget, varius nec dui. In porta risus id bibendum viverra. Pellentesque tristique quam dolor, sed tempor orci hendrerit ut. Suspendisse id lectus vel massa varius fringilla non ac orci. Etiam nec odio hendrerit, dignissim justo sed, convallis nibh. Pellentesque bibendum euismod erat, ac congue purus tincidunt eu.\nPraesent diam enim, sollicitudin quis mi id, tristique laoreet nisi. Donec faucibus tellus at libero malesuada sagittis. Quisque condimentum porta luctus. Quisque sagittis ut purus ac auctor. Nulla eget porttitor turpis, eget finibus tortor. Sed vitae convallis justo. Aenean magna felis, luctus sit amet mauris nec, lobortis aliquam risus. Duis in nisi ac sem gravida venenatis. Nullam non eros nec mauris rhoncus dapibus. Sed rhoncus ornare ligula nec placerat. Sed augue enim, semper quis sapien at, lacinia mollis nisi. Nullam pulvinar, nunc vitae suscipit euismod, lectus libero mollis massa, ut tempor enim felis non lectus.\nInteger sit amet ex quis felis pellentesque facilisis. Aliquam lacus metus, bibendum pellentesque magna quis, pellentesque vestibulum eros. Vestibulum faucibus est massa. Nunc ante massa, congue nec tortor ut, bibendum facilisis tellus. Praesent non ex et mi fermentum sollicitudin. In sollicitudin est volutpat, dictum ipsum aliquet, commodo magna. Donec et hendrerit libero, sit amet dictum leo. Nam id posuere turpis, in vulputate erat. In nec metus ut justo congue dignissim. Maecenas lobortis volutpat venenatis. Integer rhoncus dolor ut sem tempor, id sollicitudin eros viverra. Proin tincidunt finibus tincidunt.\nVestibulum vitae lacus dapibus, placerat urna non, rhoncus dolor. Maecenas pellentesque malesuada ligula nec cursus. Sed augue erat, hendrerit sed tincidunt a, facilisis id enim. Pellentesque in massa pretium, aliquam urna commodo, maximus urna. Etiam finibus nulla ac tortor scelerisque, vitae ornare neque molestie. Quisque posuere nibh vitae ante varius congue. Nullam ut ipsum auctor, dapibus justo ut, volutpat magna. Nam tristique molestie arcu in ornare. Aenean cursus pellentesque faucibus. Ut dapibus fringilla aliquam.'

In [78]:
lorem.count('a')

165

In [79]:
# 풀이

In [80]:
count = 0

for i in lorem:
    if i == 'a':
        count += 1

In [81]:
count

165

In [93]:
df = pd.read_csv("한국전력거래소_시간별 제주 풍력 발전 제어량_20211231.csv"
                 , encoding='cp949') #index_col=0

In [95]:
df.index= df['일자']

In [97]:
df.drop('일자', axis=1, inplace=True)

In [100]:
df

,횟수,1시,2시,3시,4시,5시,6시,7시,8시,9시,...,16시,17시,18시,19시,20시,21시,22시,23시,24시,총제어량
일자,,,,,,,,,,,,,,,,,,,,,
2021-01-13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,65.17
2021-01-16,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,21.75
2021-01-18,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,46.67
2021-01-19,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,36.10
2021-01-24,5,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,97.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-22,60,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,136.26
2021-10-23,61,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,50.60
2021-10-31,62,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,37.12
2021-11-03,63,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,71.97
2021-12-03,64,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,72.05

In [105]:
df2 = df.loc[['2021-01-13','2021-10-31','2021-11-03']]

In [106]:
df2

,횟수,1시,2시,3시,4시,5시,6시,7시,8시,9시,...,16시,17시,18시,19시,20시,21시,22시,23시,24시,총제어량
일자,,,,,,,,,,,,,,,,,,,,,
2021-01-13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,65.17
2021-10-31,62,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,37.12
2021-11-03,63,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,71.97

In [108]:
# True: 보여주기, False: 숨기기

df2.loc[[True,False,True]]

,횟수,1시,2시,3시,4시,5시,6시,7시,8시,9시,...,16시,17시,18시,19시,20시,21시,22시,23시,24시,총제어량
일자,,,,,,,,,,,,,,,,,,,,,
2021-01-13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,65.17
2021-11-03,63,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,71.97

In [110]:
df3=pd.DataFrame([[1,2,3],['a','b','c'],[9,'q',8]])

In [111]:
df3

   0  1  2
0  1  2  3
1  a  b  c
2  9  q  8

In [116]:
df3.loc[0] / 2

0    0.5
1    1.0
2    1.5
Name: 0, dtype: object

In [132]:
df4=pd.DataFrame([[1,2,3],['5','b',3],[9,'q',8]])

In [133]:
df4

   0  1  2
0  1  2  3
1  5  b  3
2  9  q  8

In [134]:
df4[0]

0    1
1    5
2    9
Name: 0, dtype: object

In [135]:
df4[1]

0    2
1    b
2    q
Name: 1, dtype: object

In [136]:
df4[2]

0    3
1    3
2    8
Name: 2, dtype: int64

#### dtype 을 유심히 봐야한다.
* int64 : 64 비트로 이루어진 숫자
* object : 숫자, 문자 혼합

In [142]:
df['16시']

일자
2021-01-13    0
2021-01-16    0
2021-01-18    0
2021-01-19    0
2021-01-24    3
             ..
2021-10-22    0
2021-10-23    1
2021-10-31    0
2021-11-03    0
2021-12-03    0
Name: 16시, Length: 64, dtype: int64

In [148]:
df.columns[df.loc['2021-01-24'] == 3]

Index(['12시', '16시'], dtype='object')

In [153]:
len(df.columns) # 찾을것들이 길이가 똑같아야함.

26

In [154]:
len(df.loc['2021-01-24','1시':'24시'])

24

In [157]:
df.loc['2021-01-24'] == df.loc['2021-01-24','1시':'24시'].max()

횟수      False
1시      False
2시      False
3시      False
4시      False
5시      False
6시      False
7시      False
8시      False
9시      False
10시     False
11시     False
12시     False
13시     False
14시      True
15시     False
16시     False
17시     False
18시     False
19시     False
20시     False
21시     False
22시     False
23시     False
24시     False
총제어량    False
Name: 2021-01-24, dtype: bool

In [158]:
df.columns[df.loc['2021-01-24'] == df.loc['2021-01-24','1시':'24시'].max()]

Index(['14시'], dtype='object')

# NaN, Null, 결측치

In [163]:
df2 = df[df != 0]

In [162]:
# 프로그래밍 언어에 따라 NaN, NAN, nan, null, NULL, NA, N/A. na 등으로 표기
float('nan')

nan

In [169]:
df3 = df2.dropna(axis=1, how='all') # how='all' -> 결측치만 잇는 열 제거
# axis=0 : 가로방향, axis=1: 세로방향

In [170]:
df3

            횟수  8시  9시  10시  11시   12시   13시   14시   15시  16시  17시    총제어량
일자
2021-01-13   1 NaN NaN  NaN  NaN   NaN  12.0  28.0  25.0  NaN  NaN   65.17
2021-01-16   2 NaN NaN  NaN  NaN   NaN   4.0  18.0   NaN  NaN  NaN   21.75
2021-01-18   3 NaN NaN  NaN  NaN   NaN   NaN  21.0  25.0  NaN  NaN   46.67
2021-01-19   4 NaN NaN  NaN  NaN   NaN  13.0  22.0   1.0  NaN  NaN   36.10
2021-01-24   5 NaN NaN  NaN  NaN   3.0  31.0  43.0  18.0  3.0  NaN   97.67
...         ..  ..  ..  ...  ...   ...   ...   ...   ...  ...  ...     ...
2021-10-22  60 NaN NaN  NaN  NaN   9.0  61.0  48.0  17.0  NaN  NaN  136.26
2021-10-23  61 NaN NaN  NaN  NaN  12.0  16.0  16.0   6.0  1.0  NaN   50.60
2021-10-31  62 NaN NaN  NaN  3.0   9.0  17.0   8.0   NaN  NaN  NaN   37.12
2021-11-03  63 NaN NaN  NaN  NaN  13.0  49.0  10.0   NaN  NaN  NaN   71.97
2021-12-03  64 NaN NaN  NaN  NaN   7.0  36.0  28.0   1.0  NaN  NaN   72.05

[64 rows x 12 columns]

In [171]:
df3.fillna(999) # 결측치 처리

,횟수,8시,9시,10시,11시,12시,13시,14시,15시,16시,17시,총제어량
일자,,,,,,,,,,,,
2021-01-13,1,999.0,999.0,999.0,999.0,999.0,12.0,28.0,25.0,999.0,999.0,65.17
2021-01-16,2,999.0,999.0,999.0,999.0,999.0,4.0,18.0,999.0,999.0,999.0,21.75
2021-01-18,3,999.0,999.0,999.0,999.0,999.0,999.0,21.0,25.0,999.0,999.0,46.67
2021-01-19,4,999.0,999.0,999.0,999.0,999.0,13.0,22.0,1.0,999.0,999.0,36.10
2021-01-24,5,999.0,999.0,999.0,999.0,3.0,31.0,43.0,18.0,3.0,999.0,97.67
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-22,60,999.0,999.0,999.0,999.0,9.0,61.0,48.0,17.0,999.0,999.0,136.26
2021-10-23,61,999.0,999.0,999.0,999.0,12.0,16.0,16.0,6.0,1.0,999.0,50.60
2021-10-31,62,999.0,999.0,999.0,3.0,9.0,17.0,8.0,999.0,999.0,999.0,37.12
2021-11-03,63,999.0,999.0,999.0,999.0,13.0,49.0,10.0,999.0,999.0,999.0,71.97
2021-12-03,64,999.0,999.0,999.0,999.0,7.0,36.0,28.0,1.0,999.0,999.0,72.05

In [176]:
# 0, '', ' ', 파이 기호 은 결측치로 쓰기 위험 (계산의 위험, 데이터 소실 등등)
456 * float('nan')
0 + float('nan')

nan

In [174]:
0 + float('nan')

nan

In [177]:
1==1

True

In [178]:
float('nan') == float('nan') # nan 은 무조건 nan 끼리 다름

False

In [179]:
float('nan') != float('nan')

True

# 데이터 전처리

### 데이터-> 정보: 속성이 포함되어있고 잘 정리된 것
#### 데이터 축소: 
* 차원축소;시간이 비약적으로 줄여줌, 차원축소는 필수!(너무 세세한 차이까지 찾아내기때문에, 숲보다 나무를 보는 단점)
* '1년 동안 취미를 즐긴 횟수' 23번, 42번 이런거 삭제, '최근 1년 내 취미활동을 즐겼나요?' 로 1,0 으로 수량 감소
* 데이터 속성 제거: 중복 속성 제거 (최근 일년 간 즐긴 취미, 취미 둘중 하나 제거)
* 샘플링:특정한 집단이 있을때 그 중 하나를 선정 -> 모집단, 데이터가 너무 많으면 추려서 분석, 속도 빨라짐

#### 데이터 이산화
* 연속형 데이터(스칼라): 숫자로 나타낸 값, 쪼갤 수 있는 것, 마땅한 기준x
* 범주형 데이터(카테고리컬): ex)성별
* 데이터 이산화: 연속형 데이터 -> 범주형 데이터 변경, 
* ex) 큰키:170이상, 작은키:160이하
* 데이터 이산화를 하는 이유: 컴퓨터는 판단을 못하기 때문에 직접 기준을 세워줘야함.

#### 표준화, 정규화
* 표준화(standardization): 정규분포의 속성을 갖도록 데이터 분포가 조절됨,
    데이터 범위의 제한 없음, Z-score 등
* 정규화(Normalization):
    * 그라디언트 배니싱: 딥러닝이 계산하는 과정에서 기울기가 0이 되어버리는 상황
    * 데이터의 분포 차이가 유지됨
    * 데이터 범위의 제한이 생김
    * min-max scaling 등
    * -10~999 -> 0~1 로 변환 : 정규화

## 전처리 실습

### ☆원본 - 중간산물 -결과물, 모든 코드 전부 다 가지고 있어야 함.

- 아래 데이터를 조건에 맞게 전처리해 주세요.
1. 교육대상이 성인을 포함하는지 아닌지에 따라.
2. 강좌정원수가 유의미한 차이가 있는지 알아보고 싶어요.
- raw 데이터 - 중간산물 - 전처리된 파일 까지

In [183]:
df = pd.read_csv('D:/빅데이터/시청자미디어재단_체험형미디어교육_20230704.csv',encoding='cp949')

In [184]:
df

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자,차수
0,대전시청자미디어센터,센터 체험_대전가양초등학교,강사미정,2023-07-01,2023-07-01,다문화가정 초등학생 체험/TV체험,초등학생,오프라인,토,13,2023-06-21,1
1,대전시청자미디어센터,센터 체험_노은유치원,강사미정,2023-07-04,2023-07-04,7세반 유아/TV체험,어린이,오프라인,화,25,2023-06-21,1
2,대전시청자미디어센터,센터 체험_대전성천초등학교,강사미정,2023-07-04,2023-07-04,3~4학년/TV체험,초등학생,오프라인,화,20,2023-06-21,1
3,대전시청자미디어센터,센터 체험_중리중학교(자유학년제 진로체험),강사미정,2023-07-04,2023-07-04,TV체험,중학생,오프라인,화,16,2023-06-21,1
4,대전시청자미디어센터,센터 체험_중리중학교(자유학년제 진로체험),강사미정,2023-07-04,2023-07-04,라디오체험,중학생,오프라인,화,16,2023-06-21,1
...,...,...,...,...,...,...,...,...,...,...,...,...
88,서울시청자미디어센터,방산중 미디어체험교육,"황혜정,김도경,김민호",2023-07-03,2023-07-03,"뉴스 체험, 더빙 체험, 스톱모션 체험 교육",중등,오프라인,월,75,2023-07-03,1
89,서울시청자미디어센터,상설 미디어체험교육,"김도경,이수현,이슬기",2023-07-08,2023-07-29,"뉴스 체험, 더빙 체험 교육",일반,오프라인,토,미정,2023-07-03,1
90,서울시청자미디어센터,애화학교 찾아가는 미디어 나눔버스,"이수현,이슬기",2023-07-17,2023-07-17,크로마키/ 뉴스 체험 교육,청소년,오프라인,월,미정,2023-07-03,1
91,광주시청자미디어센터,TV체험,미정,2023-01-01,2023-12-31,"방송(뉴스, 예능) 프로그램 제작 체험",일반 시민,오프라인,"월,화,수,목,금,토",30,2023-06-29,1
92,광주시청자미디어센터,라디오체험,미정,2023-01-01,2023-12-31,라디오 프로그램 제작 체험,일반 시민,오프라인,"월,화,수,목,금,토",20,2023-06-29,1

In [187]:
df['교육대상구분'].unique()

array(['초등학생', '어린이', '중학생', '고등학생', '일반시민', '초등생이상', '시니어', '초등생 이상',
       '5세이상-7세이하', '중등', '일반', '청소년', '일반 시민'], dtype=object)

In [197]:
a = df['교육대상구분'] == '일반시민'
b = df['교육대상구분'] == '시니어'
c = df['교육대상구분'] == '일반'
d = df['교육대상구분'] == '일반 시민'

In [215]:
df_a = df[a]
df_b = df[b]
df_c = df[c]
df_d = df[d]

In [216]:
df_list = [df_a, df_b, df_c, df_d]

In [217]:
df_adult = pd.concat(df_list, ignore_index=True)

In [218]:
df_adult

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자,차수
0,대전시청자미디어센터,센터 체험_국방정신전력원,강사미정,2023-07-19,2023-07-19,군인 장교 대위 교육기관/TV체험,일반시민,오프라인,수,17,2023-06-21,1
1,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-03,2023-07-03,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,월,25,2023-06-28,1
2,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-04,2023-07-04,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,화,25,2023-07-04,1
3,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-05,2023-07-05,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,수,25,2023-07-04,1
4,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-06,2023-07-06,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,목,25,2023-07-04,1
5,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-03,2023-07-03,애니메이션 더빙 체험,일반시민,오프라인,월,25,2023-07-04,1
6,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-04,2023-07-04,애니메이션 더빙 체험,일반시민,오프라인,화,25,2023-07-04,1
7,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-05,2023-07-05,애니메이션 더빙 체험,일반시민,오프라인,수,25,2023-07-04,1
8,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-06,2023-07-06,애니메이션 더빙 체험,일반시민,오프라인,목,25,2023-07-04,1
9,세종시청자미디어센터,초록TV,미정,2023-07-10,2023-07-10,유아 크로마키 체험,일반시민,오프라인,월,20,2023-07-04,1
10,세종시청자미디어센터,초록TV,미정,2023-07-11,2023-07-11,유아 크로마키 체험,일반시민,오프라인,화,20,2023-07-04,1
11,세종시청자미디어센터,초록TV,미정,2023-07-14,2023-07-14,유아 크로마키 체험,일반시민,오프라인,화,20,2023-07-04,1
12,세종시청자미디어센터,초록TV,미정,2023-07-19,2023-07-19,유아 크로마키 체험,일반시민,오프라인,수,20,2023-07-04,1
13,세종시청자미디어센터,초록TV,미정,2023-07-20,2023-07-20,유아 크로마키 체험,일반시민,오프라인,목,20,2023-07-04,1
14,세종시청자미디어센터,초록TV,미정,2023-07-21,2023-07-21,유아 크로마키 체험,일반시민,오프라인,금,20,2023-07-04,1
15,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"류은애,김은희",2023-07-14,2023-07-14,TV 뉴스 제작 및 영상합성 크로마키 체험,일반시민,오프라인,금,60,2023-07-04,1
16,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"이해인,강진경",2023-07-15,2023-07-15,TV 뉴스 제작 및 영상합성 크로마키 체험,일반시민,오프라인,토,60,2023-07-04,1
17,부산시청자미디어센터,라디오체험(웰컴투라디오),미정,2023-07-01,2023-07-31,라디오 프로그램 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
18,부산시청자미디어센터,더빙체험(나도 애니주인공),미정,2023-07-01,2023-07-31,애니메이션 더빙 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
19,부산시청자미디어센터,스마트체험(꼼지락애니),미정,2023-07-01,2023-07-31,스톱모션 애니메이션 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
20,부산시청자미디어센터,TV체험(행복뉴스),미정,2023-07-01,2023-07-31,방송뉴스 프로그램 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
21,부산시청자미디어센터,크로마키체험(파랑TV),미정,2023-07-01,2023-07-31,크로마키 합성을 이용한 놀이형 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
22,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"박지원,김지원",2023-07-12,2023-07-12,TV 뉴스 제작 및 영상합성 크로마키 체험,시니어,오프라인,수,30,2023-07-04,1
23,서울시청자미디어센터,상설 미디어체험교육,"김도경,이수현,이슬기",2023-07-08,2023-07-29,"뉴스 체험, 더빙 체험 교육",일반,오프라인,토,미정,2023-07-03,1
24,광주시청자미디어센터,TV체험,미정,2023-01-01,2023-12-31,"방송(뉴스, 예능) 프로그램 제작 체험",일반 시민,오프라인,"월,화,수,목,금,토",30,2023-06-29,1
25,광주시청자미디어센터,라디오체험,미정,2023-01-01,2023-12-31,라디오 프로그램 제작 체험,일반 시민,오프라인,"월,화,수,목,금,토",20,2023-06-29,1

In [206]:
df[c]

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자,차수
89,서울시청자미디어센터,상설 미디어체험교육,"김도경,이수현,이슬기",2023-07-08,2023-07-29,"뉴스 체험, 더빙 체험 교육",일반,오프라인,토,미정,2023-07-03,1

# 풀이

In [208]:
df['교육대상구분'].unique()

array(['초등학생', '어린이', '중학생', '고등학생', '일반시민', '초등생이상', '시니어', '초등생 이상',
       '5세이상-7세이하', '중등', '일반', '청소년', '일반 시민'], dtype=object)

In [210]:
target = ['일반시민','시니어','일반','일반 시민', '초등생이상', '초등생 이상']

In [212]:
'어린이' in target

False

In [213]:
m = df['교육대상구분'].apply(lambda x: x in target)

In [219]:
df2 = df[m] # 성인이 들어있는 데이터

In [222]:
def to_int(x):
    try:
        return int(x)
    except:
        return 0

In [224]:
df2['강좌정원수'] = df2['강좌정원수'].apply(lambda x: to_int(x))

C:\Users\leah5\AppData\Local\Temp\ipykernel_4276\3016817227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['강좌정원수'] = df2['강좌정원수'].apply(lambda x: to_int(x))

In [ ]:
# 사용자 지정 warning

### 깊은 복사, deep copy, ex) 판다스 데이터프레임

In [225]:
x=123

In [226]:
y=x

In [227]:
y+=1

In [228]:
x,y

(123, 124)

In [229]:
list1=[1,2,3]

In [230]:
list2=list1

In [232]:
list2[2] = 999

In [233]:
list1, list2

([1, 2, 999], [1, 2, 999])

In [236]:
df2

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자,차수
12,대전시청자미디어센터,센터 체험_국방정신전력원,강사미정,2023-07-19,2023-07-19,군인 장교 대위 교육기관/TV체험,일반시민,오프라인,수,17,2023-06-21,1
14,울산시청자미디어센터,오늘은 NEWS데이,"김윤아,권석진",2023-07-04,2023-07-04,크로마키를 활용한 미디어 직업 체험,초등생이상,오프라인,화,25,2023-06-27,1
15,울산시청자미디어센터,DJ수다박스,"김은희,김병준",2023-07-04,2023-07-04,라디오 프로그램 제작 체험,초등생이상,오프라인,화,25,2023-06-27,1
16,울산시청자미디어센터,찰칵 애니,"김현주,도현정",2023-07-04,2023-07-04,스톱모션 기술을 이용한 애니메이션 제작 체험,초등생이상,오프라인,화,25,2023-06-27,1
17,울산시청자미디어센터,알고리즘+빅데이터,이창수,2023-07-04,2023-07-04,"알고리즘 분석을 통한 비판적 정보탐색 역량강화 체험, 데이터를 모으고 시각화하는 과...",초등생이상,오프라인,화,25,2023-06-27,1
18,울산시청자미디어센터,오늘은 NEWS데이,"박민주,안지현",2023-07-05,2023-07-05,크로마키를 활용한 미디어 직업 체험,초등생이상,오프라인,수,25,2023-06-27,1
19,울산시청자미디어센터,DJ수다박스,"장미경,공상혁",2023-07-05,2023-07-05,라디오 프로그램 제작 체험,초등생이상,오프라인,수,25,2023-06-27,1
20,울산시청자미디어센터,빅데이터,전윤겸,2023-07-05,2023-07-05,데이터를 모으고 시각화하는 과정을 배울수 있는 미디어 신기술 체험,초등생이상,오프라인,수,25,2023-06-27,1
21,울산시청자미디어센터,찰칵 애니,"김윤아,김은희",2023-07-05,2023-07-05,스톱모션 기술을 이용한 애니메이션 제작 체험,초등생이상,오프라인,수,25,2023-06-27,1
22,울산시청자미디어센터,알고리즘,이창수,2023-07-05,2023-07-05,알고리즘 분석을 통한 비판적 정보탐색 역량강화 체험,초등생이상,오프라인,수,25,2023-06-27,1
23,울산시청자미디어센터,오늘은 NEWS데이,"강선화,권석진",2023-07-06,2023-07-06,크로마키를 활용한 미디어 직업 체험,초등생이상,오프라인,목,25,2023-06-27,1
24,울산시청자미디어센터,DJ수다박스,"장현,김병준",2023-07-06,2023-07-06,라디오 프로그램 제작 체험,초등생이상,오프라인,목,25,2023-06-27,1
25,울산시청자미디어센터,찰칵 애니,"도현정,김현주",2023-07-06,2023-07-06,스톱모션 기술을 이용한 애니메이션 제작 체험,초등생이상,오프라인,목,25,2023-06-27,1
28,울산시청자미디어센터,초록세상 마법학교,"장미경,이창수",2023-07-12,2023-07-12,크로마키를 활용한 영상 합성 체험,초등생이상,오프라인,수,25,2023-06-27,1
29,울산시청자미디어센터,오늘은 NEWS데이,"김윤아,김병준",2023-07-15,2023-07-15,크로마키를 활용한 미디어 직업 체험,초등생이상,오프라인,토,25,2023-06-27,1
30,울산시청자미디어센터,DJ 수다박스,"김은희,안지현",2023-07-15,2023-07-15,라디오 프로그램 제작 체험,초등생이상,오프라인,토,25,2023-06-27,1
31,울산시청자미디어센터,오늘은 NEWS데이,"김현주,이창수",2023-07-18,2023-07-18,크로마키를 활용한 미디어 직업 체험,초등생이상,오프라인,화,25,2023-06-27,1
32,울산시청자미디어센터,DJ 수다박스,"도현정,권석진",2023-07-18,2023-07-18,라디오 프로그램 제작 체험,초등생이상,오프라인,화,25,2023-06-27,1
33,울산시청자미디어센터,빅데이터,전윤겸,2023-07-18,2023-07-18,데이터를 모으고 시각화하는 과정을 배울수 있는 미디어 신기술 체험,초등생이상,오프라인,화,25,2023-06-27,1
35,울산시청자미디어센터,찰칵 애니,"김현주,도현정",2023-07-19,2023-07-19,스톱모션 기술을 이용한 애니메이션 제작 체험,초등생이상,오프라인,수,25,2023-06-27,1
37,울산시청자미디어센터,더빙극장,"김윤아,이창수",2023-07-22,2023-07-22,애니메이션을 활용한 더빙 체험,초등생이상,오프라인,토,25,2023-06-27,1
39,울산시청자미디어센터,DJ 수다박스,"박민주, 권석진",2023-07-26,2023-07-26,라디오 프로그램 제작 체험,초등생이상,오프라인,수,25,2023-06-27,1
45,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-03,2023-07-03,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,월,25,2023-06-28,1
46,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-04,2023-07-04,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,화,25,2023-07-04,1
47,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-05,2023-07-05,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,수,25,2023-07-04,1
48,세종시청자미디어센터,골라보는 뉴스룸,미정,2023-07-06,2023-07-06,"아나운서, 기자, 방송인 직업체험",일반시민,오프라인,목,25,2023-07-04,1
49,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-03,2023-07-03,애니메이션 더빙 체험,일반시민,오프라인,월,25,2023-07-04,1
50,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-04,2023-07-04,애니메이션 더빙 체험,일반시민,오프라인,화,25,2023-07-04,1
51,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-05,2023-07-05,애니메이션 더빙 체험,일반시민,오프라인,수,25,2023-07-04,1
52,세종시청자미디어센터,두다다다 더빙탐험대,미정,2023-07-06,2023-07-06,애니메이션 더빙 체험,일반시민,오프라인,목,25,2023-07-04,1
53,세종시청자미디어센터,초록TV,미정,2023-07-10,2023-07-10,유아 크로마키 체험,일반시민,오프라인,월,20,2023-07-04,1
54,세종시청자미디어센터,초록TV,미정,2023-07-11,2023-07-11,유아 크로마키 체험,일반시민,오프라인,화,20,2023-07-04,1
55,세종시청자미디어센터,초록TV,미정,2023-07-14,2023-07-14,유아 크로마키 체험,일반시민,오프라인,화,20,2023-07-04,1
56,세종시청자미디어센터,초록TV,미정,2023-07-19,2023-07-19,유아 크로마키 체험,일반시민,오프라인,수,20,2023-07-04,1
57,세종시청자미디어센터,초록TV,미정,2023-07-20,2023-07-20,유아 크로마키 체험,일반시민,오프라인,목,20,2023-07-04,1
58,세종시청자미디어센터,초록TV,미정,2023-07-21,2023-07-21,유아 크로마키 체험,일반시민,오프라인,금,20,2023-07-04,1
61,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"박지원,김지원",2023-07-12,2023-07-12,TV 뉴스 제작 및 영상합성 크로마키 체험,시니어,오프라인,수,30,2023-07-04,1
63,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"류은애,김은희",2023-07-14,2023-07-14,TV 뉴스 제작 및 영상합성 크로마키 체험,일반시민,오프라인,금,60,2023-07-04,1
64,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"이해인,강진경",2023-07-15,2023-07-15,TV 뉴스 제작 및 영상합성 크로마키 체험,일반시민,오프라인,토,60,2023-07-04,1
70,충북시청자미디어센터,TV체험(뉴스체험),미정,2023-05-02,2023-05-31,"아나운서, 기자, 기상캐스터 등 역할을 나누어 뉴스 제작 과정을 체험해보는 프로그램",초등생 이상,오프라인,"월,화,수,목,금,토",15,2023-06-29,1
71,충북시청자미디어센터,라디오체험(DJ체험),미정,2023-05-02,2023-05-31,"라디오 프로그램을 작가, DJ, 게스트가 되어 라디오 프로그램을 제작해보는 체험",초등생 이상,오프라인,"월,화,수,목,금,토",15,2023-06-29,1
73,충북시청자미디어센터,폴리아티스트 체험,미정,2023-05-02,2023-05-31,영상에 어울리는 소리를 다양한 재료로 만들어보고 더빙해보는 체험,초등생 이상,오프라인,"월,화,수,목,금,토",15,2023-06-29,1
74,충북시청자미디어센터,AI 체험,미정,2023-05-02,2023-05-31,인공지능에 대해 이해하고 머신러닝을 여러 방법으로 알아보는 체험,초등생 이상,오프라인,"월,화,수,목,금,토",15,2023-06-29,1
75,충북시청자미디어센터,라이브커머스체험,미정,2023-05-02,2023-05-31,라이브커머스의 이해 및 체험,초등생 이상,오프라인,"월,화,수,목,금,토",15,2023-06-29,1
80,부산시청자미디어센터,라디오체험(웰컴투라디오),미정,2023-07-01,2023-07-31,라디오 프로그램 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
81,부산시청자미디어센터,더빙체험(나도 애니주인공),미정,2023-07-01,2023-07-31,애니메이션 더빙 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
82,부산시청자미디어센터,스마트체험(꼼지락애니),미정,2023-07-01,2023-07-31,스톱모션 애니메이션 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
83,부산시청자미디어센터,TV체험(행복뉴스),미정,2023-07-01,2023-07-31,방송뉴스 프로그램 제작 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
84,부산시청자미디어센터,크로마키체험(파랑TV),미정,2023-07-01,2023-07-31,크로마키 합성을 이용한 놀이형 체험,일반시민,오프라인,"월,화,수,목,금,토",20,2023-06-30,1
89,서울시청자미디어센터,상설 미디어체험교육,"김도경,이수현,이슬기",2023-07-08,2023-07-29,"뉴스 체험, 더빙 체험 교육",일반,오프라인,토,0,2023-07-03,1
91,광주시청자미디어센터,TV체험,미정,2023-01-01,2023-12-31,"방송(뉴스, 예능) 프로그램 제작 체험",일반 시민,오프라인,"월,화,수,목,금,토",30,2023-06-29,1
92,광주시청자미디어센터,라디오체험,미정,2023-01-01,2023-12-31,라디오 프로그램 제작 체험,일반 시민,오프라인,"월,화,수,목,금,토",20,2023-06-29,1

In [237]:
df2['강좌정원수'].mean()

23.78846153846154

- 함부로 float로 바꾸면 안됨!!! 파이썬은 부동소수점으로 숫자를 처리하기때문에 정수를 실수처리하면 이상한값이 들어가서 그게 쌓이면 계산에 오류가 생김.
- 그래서 딥러닝 모델도 A확률 %, B확률 % 이렇게 대답하는 거임.